apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudquery.secret" . }}
  labels:
  {{- include "cloudquery.labels" . | nindent 4 }}
data:
  CQ_DSN: {{ .Values.config.dsn | b64enc | quote }}
{{- range $k, $v := .Values.config.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
